#!/usr/bin/env bash
# t.me/kusky

source colors 2>/dev/null || echo 'missing "colors" dependency'

pic=$1
rate="10"

echo -e $blue::$reset "Waiting for input..."
echo -e $blue::$reset Fetching input every $rate\s...

while true; do
	if [ -s $pic ]; then
	timeout 9 sxiv $pic
	rm $pic
	fi
	sleep $rate
done
